<?php

namespace App\Filament\Resources\Themes\Support;
class ThemePresets
{
    public static function getPresets(): array
    {
        return [
            'filament_default' => [
                'label'        => 'Filament Default',
                'swatch_light' => '#6366f1',
                'swatch_dark'  => '#818cf8',
                'description'  => 'Paleta oficial de Filament — deja todos los valores vacíos',
                'light' => [
                    'base_color'       => null,
                    'background_color' => null,
                    'text_color'       => null,
                    'primary_color'    => null,
                    'secondary_color'  => null,
                    'success_color'    => null,
                    'warning_color'    => null,
                    'danger_color'     => null,
                    'info_color'       => null,
                ],
                'dark' => [
                    'base_color'       => null,
                    'background_color' => null,
                    'text_color'       => null,
                    'primary_color'    => null,
                    'secondary_color'  => null,
                    'success_color'    => null,
                    'warning_color'    => null,
                    'danger_color'     => null,
                    'info_color'       => null,
                ],
            ],

            'green_nature' => [
                'label'        => 'Verde Naturaleza',
                'swatch_light' => '#16a34a',
                'swatch_dark'  => '#4ade80',
                'description'  => 'Verdes frescos inspirados en la naturaleza',
                'light' => [
                    'base_color'       => '#f0fdf4',
                    'background_color' => '#f0fdf4',
                    'text_color'       => '#14532d',
                    'primary_color'    => '#16a34a',
                    'secondary_color'  => '#65a30d',
                    'success_color'    => '#15803d',
                    'warning_color'    => '#ca8a04',
                    'danger_color'     => '#dc2626',
                    'info_color'       => '#0891b2',
                ],
                'dark' => [
                    'base_color'       => '#052e16',
                    'background_color' => '#052e16',
                    'text_color'       => '#dcfce7',
                    'primary_color'    => '#4ade80',
                    'secondary_color'  => '#a3e635',
                    'success_color'    => '#86efac',
                    'warning_color'    => '#fde047',
                    'danger_color'     => '#fca5a5',
                    'info_color'       => '#67e8f9',
                ],
            ],

            'green_mint' => [
                'label'        => 'Verde Menta',
                'swatch_light' => '#0d9488',
                'swatch_dark'  => '#2dd4bf',
                'description'  => 'Menta suave y moderna, look clínico/fresco',
                'light' => [
                    'base_color'       => '#f0fdfa',
                    'background_color' => '#f0fdfa',
                    'text_color'       => '#134e4a',
                    'primary_color'    => '#0d9488',
                    'secondary_color'  => '#059669',
                    'success_color'    => '#10b981',
                    'warning_color'    => '#d97706',
                    'danger_color'     => '#e11d48',
                    'info_color'       => '#0284c7',
                ],
                'dark' => [
                    'base_color'       => '#042f2e',
                    'background_color' => '#042f2e',
                    'text_color'       => '#ccfbf1',
                    'primary_color'    => '#2dd4bf',
                    'secondary_color'  => '#34d399',
                    'success_color'    => '#6ee7b7',
                    'warning_color'    => '#fcd34d',
                    'danger_color'     => '#fb7185',
                    'info_color'       => '#38bdf8',
                ],
            ],

            'ocean_blue' => [
                'label'        => 'Azul Océano',
                'swatch_light' => '#2563eb',
                'swatch_dark'  => '#60a5fa',
                'description'  => 'Azules profundos, profesional y confiable',
                'light' => [
                    'base_color'       => '#eff6ff',
                    'background_color' => '#eff6ff',
                    'text_color'       => '#1e3a5f',
                    'primary_color'    => '#2563eb',
                    'secondary_color'  => '#0ea5e9',
                    'success_color'    => '#16a34a',
                    'warning_color'    => '#d97706',
                    'danger_color'     => '#dc2626',
                    'info_color'       => '#0284c7',
                ],
                'dark' => [
                    'base_color'       => '#0c1a2e',
                    'background_color' => '#0c1a2e',
                    'text_color'       => '#dbeafe',
                    'primary_color'    => '#60a5fa',
                    'secondary_color'  => '#38bdf8',
                    'success_color'    => '#4ade80',
                    'warning_color'    => '#fbbf24',
                    'danger_color'     => '#f87171',
                    'info_color'       => '#7dd3fc',
                ],
            ],

            'sky_blue' => [
                'label'        => 'Azul Cielo',
                'swatch_light' => '#0369a1',
                'swatch_dark'  => '#38bdf8',
                'description'  => 'Cielo claro, limpio y minimalista',
                'light' => [
                    'base_color'       => '#f0f9ff',
                    'background_color' => '#f0f9ff',
                    'text_color'       => '#0c4a6e',
                    'primary_color'    => '#0369a1',
                    'secondary_color'  => '#6366f1',
                    'success_color'    => '#059669',
                    'warning_color'    => '#b45309',
                    'danger_color'     => '#be123c',
                    'info_color'       => '#0891b2',
                ],
                'dark' => [
                    'base_color'       => '#082f49',
                    'background_color' => '#082f49',
                    'text_color'       => '#e0f2fe',
                    'primary_color'    => '#38bdf8',
                    'secondary_color'  => '#818cf8',
                    'success_color'    => '#34d399',
                    'warning_color'    => '#fcd34d',
                    'danger_color'     => '#fb7185',
                    'info_color'       => '#22d3ee',
                ],
            ],

            'rose_pink' => [
                'label'        => 'Rosa',
                'swatch_light' => '#e11d48',
                'swatch_dark'  => '#fb7185',
                'description'  => 'Rosa elegante, vibrante y moderno',
                'light' => [
                    'base_color'       => '#fff1f2',
                    'background_color' => '#fff1f2',
                    'text_color'       => '#4c0519',
                    'primary_color'    => '#e11d48',
                    'secondary_color'  => '#db2777',
                    'success_color'    => '#16a34a',
                    'warning_color'    => '#d97706',
                    'danger_color'     => '#9f1239',
                    'info_color'       => '#0891b2',
                ],
                'dark' => [
                    'base_color'       => '#1f0010',
                    'background_color' => '#1f0010',
                    'text_color'       => '#ffe4e6',
                    'primary_color'    => '#fb7185',
                    'secondary_color'  => '#f472b6',
                    'success_color'    => '#4ade80',
                    'warning_color'    => '#fbbf24',
                    'danger_color'     => '#fda4af',
                    'info_color'       => '#67e8f9',
                ],
            ],

            'warm_brown' => [
                'label'        => 'Marrón Cálido',
                'swatch_light' => '#92400e',
                'swatch_dark'  => '#d97706',
                'description'  => 'Tierra y madera, cálido y acogedor',
                'light' => [
                    'base_color'       => '#fdf8f0',
                    'background_color' => '#fdf8f0',
                    'text_color'       => '#3b1f0a',
                    'primary_color'    => '#92400e',
                    'secondary_color'  => '#b45309',
                    'success_color'    => '#15803d',
                    'warning_color'    => '#ca8a04',
                    'danger_color'     => '#b91c1c',
                    'info_color'       => '#0369a1',
                ],
                'dark' => [
                    'base_color'       => '#1c0f06',
                    'background_color' => '#1c0f06',
                    'text_color'       => '#fef3c7',
                    'primary_color'    => '#d97706',
                    'secondary_color'  => '#f59e0b',
                    'success_color'    => '#4ade80',
                    'warning_color'    => '#fde047',
                    'danger_color'     => '#fca5a5',
                    'info_color'       => '#7dd3fc',
                ],
            ],

            'purple_grape' => [
                'label'        => 'Púrpura',
                'swatch_light' => '#7c3aed',
                'swatch_dark'  => '#a78bfa',
                'description'  => 'Morado intenso, creativo y sofisticado',
                'light' => [
                    'base_color'       => '#faf5ff',
                    'background_color' => '#faf5ff',
                    'text_color'       => '#2e1065',
                    'primary_color'    => '#7c3aed',
                    'secondary_color'  => '#a21caf',
                    'success_color'    => '#15803d',
                    'warning_color'    => '#b45309',
                    'danger_color'     => '#be123c',
                    'info_color'       => '#0369a1',
                ],
                'dark' => [
                    'base_color'       => '#13002e',
                    'background_color' => '#13002e',
                    'text_color'       => '#f3e8ff',
                    'primary_color'    => '#a78bfa',
                    'secondary_color'  => '#e879f9',
                    'success_color'    => '#4ade80',
                    'warning_color'    => '#fbbf24',
                    'danger_color'     => '#fb7185',
                    'info_color'       => '#38bdf8',
                ],
            ],

            'sunset_orange' => [
                'label'        => 'Naranja Atardecer',
                'swatch_light' => '#ea580c',
                'swatch_dark'  => '#fb923c',
                'description'  => 'Naranja vivo y energético, estilo startup',
                'light' => [
                    'base_color'       => '#fff7ed',
                    'background_color' => '#fff7ed',
                    'text_color'       => '#431407',
                    'primary_color'    => '#ea580c',
                    'secondary_color'  => '#d97706',
                    'success_color'    => '#16a34a',
                    'warning_color'    => '#ca8a04',
                    'danger_color'     => '#dc2626',
                    'info_color'       => '#0284c7',
                ],
                'dark' => [
                    'base_color'       => '#1a0a00',
                    'background_color' => '#1a0a00',
                    'text_color'       => '#ffedd5',
                    'primary_color'    => '#fb923c',
                    'secondary_color'  => '#fbbf24',
                    'success_color'    => '#4ade80',
                    'warning_color'    => '#fde047',
                    'danger_color'     => '#fca5a5',
                    'info_color'       => '#7dd3fc',
                ],
            ],

            'slate_minimal' => [
                'label'        => 'Slate Minimal',
                'swatch_light' => '#334155',
                'swatch_dark'  => '#94a3b8',
                'description'  => 'Gris neutro, ultra limpio y profesional',
                'light' => [
                    'base_color'       => '#f8fafc',
                    'background_color' => '#f8fafc',
                    'text_color'       => '#0f172a',
                    'primary_color'    => '#334155',
                    'secondary_color'  => '#475569',
                    'success_color'    => '#16a34a',
                    'warning_color'    => '#d97706',
                    'danger_color'     => '#dc2626',
                    'info_color'       => '#0284c7',
                ],
                'dark' => [
                    'base_color'       => '#0f172a',
                    'background_color' => '#0f172a',
                    'text_color'       => '#f1f5f9',
                    'primary_color'    => '#94a3b8',
                    'secondary_color'  => '#64748b',
                    'success_color'    => '#4ade80',
                    'warning_color'    => '#fbbf24',
                    'danger_color'     => '#f87171',
                    'info_color'       => '#60a5fa',
                ],
            ],
        ];
    }
}